---
title: "Website Workflow using .Rmd and GitHub Pages"
author: Joanna Schroeder
date: DSPG 2023 Training <br> July 5 2023
output: slidy_presentation
footer: "<a href = './index.html'>Go back to the demo site</a>"
---

# Today's agenda

- Assumed knowledge
- What are we doing
- Good resources
- Creating a bare-bones website
- Options for customization
- Deploying

# Assumed knowledge

- RMarkdowns (.Rmds)
  - Rmd syntax
- Git and GitHub
- Bonus: Any knowledge of web languages
  - HTML, CSS, and JavaScript
  - This can be a great way to learn!

# What are we doing

- Goal: Understand the workflow of creating a website with Rmds and GitHub Pages

- In addition to being a great way to write [literate programs](https://books.ropensci.org/targets/literate-programming.html), Rmd supports a variety of output formats
  - Including HTML!
- We can use YAML + Rmds to build a website
  - YAML brings the organization
  - Rmds bring the content
- Bonus: We can add customizations
  - Themes
  - Custom stylesheets (CSS)
  - Custom HTML/Javascript

# Good resources

- [GitHub's GitHub Pages Overview](https://pages.github.com/)
- [rstudio4edu's RMarkdown Sites Cookbook](https://rstudio4edu.github.io/rstudio4edu-book/intro-rmd.html)
- [Emily Zabor's R Websites Tutorial](https://www.emilyzabor.com/tutorials/rmarkdown_websites_tutorial.html#Types_of_websites)
- [The RMarkdown Cookbook](https://bookdown.org/yihui/rmarkdown-cookbook/)
- [W3Schools](https://www.w3schools.com/)

# Creating a bare-bones website

We will need

- A YAML file
  - [From RedHat:](https://www.redhat.com/en/topics/automation/what-is-yaml#:~:text=YAML%20is%20a%20human%2Dreadable,is%20for%20data%2C%20not%20documents.) YAML is a human-readable data serialization language that is often used for writing configuration files.
  Depending on whom you ask, YAML stands for yet another markup language or YAML ain’t markup language (a recursive
  acronym), which emphasizes that YAML is for data, not documents. 
- An index file
  - index.Rmd which will knit into index.html
  - Automatic homepage
  
From your \web directory\*, run `rmarkdown::render_site()` to autopopulate files

\* You will want to consider your directory structure (specific to project needs)

# Options for customization

- [RMarkdown Themes](https://www.datadreaming.org/post/r-markdown-theme-gallery/)
- [Templates](https://github.com/topics/personal-website)
  - Some of these are [Jekyll themes](https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/about-github-pages-and-jekyll)
  - [Joanna's ancient site example](https://github.com/jo-schroeder/jo-schroeder.github.io)
- Inline CSS
- [Linked](https://github.com/uva-bi-sdad/sdc.intro/blob/main/src/web/_site.yml#L7) [CSS stylesheets](https://github.com/uva-bi-sdad/sdc.intro/blob/main/src/web/style.css)
- [Custom HTML](https://github.com/uva-bi-sdad/sdc.intro/blob/main/src/web/data.Rmd#L11)
- [Custom Javascript](https://github.com/uva-bi-sdad/sdc.intro/blob/main/src/web/health_equity_beta.Rmd#L1)

- Note: VERY HACKY

# Deploying

- Make sure your changes have been knit
  - Hint: Hit the hammer!
- Hosting with GitHub pages
  - Limited to one root site per organization or user, unlimited "project" sites
  - You can only host a GitHub Pages website from a public repo
- From your repository Settings click Pages
  - Select Deploy from Branch (or GitHub Actions)
  - Select your main branch and \docs folder (where the knitted .html files live)
  - Here's where you can add a custom domain name
